[project]
name = "id3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pyyaml>=6.0.3",
    "torch==2.9.0",
    "tqdm>=4.67.1",
    "viennarna>=2.7.0",
]
